"""Machine-readable built-in catalog and safe declarative construction."""

from aberrant.catalog._config import (
    CONFIG_FORMAT_VERSION,
    ComponentConfig,
    DetectorConfig,
    build_detector,
    create_model,
    create_similarity_engine,
    create_transformer,
    detector_capabilities,
    normalize_detector_config,
)
from aberrant.catalog._registry import (
    CATALOG_FORMAT_VERSION,
    MODEL_CATALOG,
    SIMILARITY_ENGINE_CATALOG,
    TRANSFORMER_CATALOG,
    catalog_manifest,
    get_model_spec,
    get_similarity_engine_spec,
    get_transformer_spec,
)
from aberrant.catalog._specs import (
    ComponentDependency,
    ComponentKind,
    ComponentSpec,
    EventKind,
    FeatureCount,
    FeatureSchemaKind,
    ModelCapabilities,
    ModelSpec,
    ScoreKind,
    StateKind,
    TransformerSpec,
    WarmupRequirement,
    WarmupUnit,
)

__all__ = [
    "CATALOG_FORMAT_VERSION",
    "CONFIG_FORMAT_VERSION",
    "MODEL_CATALOG",
    "SIMILARITY_ENGINE_CATALOG",
    "TRANSFORMER_CATALOG",
    "ComponentConfig",
    "ComponentDependency",
    "ComponentKind",
    "ComponentSpec",
    "DetectorConfig",
    "EventKind",
    "FeatureCount",
    "FeatureSchemaKind",
    "ModelCapabilities",
    "ModelSpec",
    "ScoreKind",
    "StateKind",
    "TransformerSpec",
    "WarmupRequirement",
    "WarmupUnit",
    "build_detector",
    "catalog_manifest",
    "create_model",
    "create_similarity_engine",
    "create_transformer",
    "detector_capabilities",
    "get_model_spec",
    "get_similarity_engine_spec",
    "get_transformer_spec",
    "normalize_detector_config",
]
